// import { Roboto } from 'next/font/google';
import Navbar from "@/components/Shared/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Shared/Footer";

// // ✅ Roboto font config
// const roboto = Roboto({
//   variable: '--font-roboto',
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'],
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
