// import { Roboto } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from '@/components/Shared/Navbar/Navbar';
import Footer from "@/components/Shared/Footer/Footer";

// // ✅ Roboto font config
// const roboto = Roboto({
//   variable: '--font-roboto',
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'],
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider>
          {/* fixed navbar */}
          <header>
            <Navbar />
          </header>

          {/* main content */}
          <main>{children}</main>

          {/* fixed footer */}
          <footer><Footer /></footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
